name: Rust

on:
  push:
    branches:
      - main

permissions:
  contents: write

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
    - name: Generate Docs
      run: cargo doc --verbose
    - name: Publish Docs
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        folder: target/docs/
